from datetime import datetime
from pathlib import Path

from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime
from sqlalchemy.orm import declarative_base, sessionmaker

# Make sure a "data" folder exists in the project root — this is where
# the SQLite database file will physically live. exist_ok=True means
# "don't error out if the folder is already there."
Path("data").mkdir(exist_ok=True)

# The connection string SQLAlchemy uses to talk to the database.
# "sqlite:///data/chatbot_memory.db" tells it: use SQLite, and store
# the actual .db file at data/chatbot_memory.db (relative path).
DATABASE_URL = "sqlite:///data/chatbot_memory.db"

# The "engine" is the core interface between SQLAlchemy and the actual
# database — every query eventually goes through this.
engine = create_engine(
    DATABASE_URL,
    # SQLite only allows a connection to be used by the thread that
    # created it, by default. A web server (like FastAPI) can handle
    # requests on different threads, so this flag turns that safety
    # check off. It's a known, accepted workaround for SQLite + web apps.
    connect_args={"check_same_thread": False}
)

# sessionmaker() doesn't create a session itself — it creates a
# *factory* for sessions. Every time you call SessionLocal(), you get
# a brand new "conversation" with the database that you can query,
# add rows to, commit, and close.
# autoflush=False / autocommit=False: don't auto-save changes; we'll
# call db.commit() explicitly when we're ready.
SessionLocal = sessionmaker(bind=engine, autoflush=False, autocommit=False)

# Base is the parent class that all our table models below inherit
# from. This is how SQLAlchemy knows a Python class like
# "Conversation" actually maps to a real database table.
Base = declarative_base()


# ---- TABLE 1: one row per chat thread/session ----
class Conversation(Base):
    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    # thread_id is how we uniquely identify a specific chat session
    # (e.g. a UUID generated by the frontend). unique=True enforces
    # no duplicates; index=True speeds up lookups by this column.
    thread_id = Column(String, unique=True, index=True)
    # Shown in a chat list/sidebar in the UI. Defaults to "New Chat"
    # until we have a real first message to derive a title from.
    title = Column(String, default="New Chat")
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)


# ---- TABLE 2: every individual message in every conversation ----
class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(Integer, primary_key=True, index=True)
    # Which conversation this message belongs to (not unique — a
    # thread has many messages, so no unique=True here).
    thread_id = Column(String, index=True)
    # "user" or "assistant" — lets us reconstruct who said what when
    # rebuilding chat history to feed back into the LLM.
    role = Column(String)
    content = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


# ---- TABLE 3: long-term "memory" facts, separate from raw chat logs ----
class LongTermMemory(Base):
    __tablename__ = "long_term_memory"

    id = Column(Integer, primary_key=True, index=True)
    thread_id = Column(String, index=True)
    # Free-text memory content — e.g. "user prefers concise answers"
    # or "user is building a PDF editor app". This is what an agent
    # would consult before responding, separate from just replaying
    # the full chat transcript.
    memory = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


def init_db():
    """
    Actually creates the tables in the SQLite file based on the models
    defined above, but only if they don't already exist. Call this
    once when your app starts up (e.g. in FastAPI's startup event).
    """
    Base.metadata.create_all(bind=engine)


def create_or_update_conversation(thread_id: str, first_message: str | None = None):
    """
    Called whenever a chat message comes in. If this thread_id is new,
    creates a Conversation row (and derives a title from the first
    message). If it already exists, just bumps the updated_at
    timestamp so conversation lists can sort by "most recently active".
    """
    db = SessionLocal()

    try:
        # Look for an existing conversation with this thread_id.
        conversation = (
            db.query(Conversation)
            .filter(Conversation.thread_id == thread_id)
            .first()
        )

        if not conversation:
            title = "New Chat"

            if first_message:
                # Use the first ~40 characters of the first message as
                # a human-readable title, with "..." if it was cut off.
                title = first_message.strip()[:40]
                if len(first_message.strip()) > 40:
                    title += "..."

            conversation = Conversation(
                thread_id=thread_id,
                title=title,
                created_at=datetime.utcnow(),
                updated_at=datetime.utcnow()
            )

            db.add(conversation)  # stage the new row for insertion

        else:
            # Conversation already exists — just mark it as recently active.
            conversation.updated_at = datetime.utcnow()

        db.commit()  # actually write the change(s) to the database

    finally:
        # Always close the session, even if an error was raised above,
        # so we don't leak open database connections.
        db.close()


def list_conversations():
    """
    Returns all conversations, most recently updated first.
    Useful for rendering a sidebar/history list in a UI.
    """
    db = SessionLocal()

    try:
        return (
            db.query(Conversation)
            .order_by(Conversation.updated_at.desc())
            .all()
        )

    finally:
        db.close()


def save_chat_message(thread_id: str, role: str, content: str):
    """
    Persists a single message (user or assistant) to the database,
    and updates the parent conversation's updated_at timestamp.
    """
    db = SessionLocal()

    try:
        msg = ChatMessage(
            thread_id=thread_id,
            role=role,
            content=content,
            created_at=datetime.utcnow()
        )

        db.add(msg)

        # Also touch the parent conversation's timestamp, so it moves
        # to the top of "most recent" lists.
        conversation = (
            db.query(Conversation)
            .filter(Conversation.thread_id == thread_id)
            .first()
        )

        if conversation:
            conversation.updated_at = datetime.utcnow()

        db.commit()

    finally:
        db.close()


def get_chat_history(thread_id: str):
    """
    Fetches every message for a given thread, oldest first — this is
    what you'd feed back into the LLM as conversation context on each
    new turn, so it "remembers" what was said earlier in the chat.
    """
    db = SessionLocal()

    try:
        return (
            db.query(ChatMessage)
            .filter(ChatMessage.thread_id == thread_id)
            .order_by(ChatMessage.created_at.asc())
            .all()
        )

    finally:
        db.close()


def save_memory(thread_id: str, memory: str):
    """
    Stores a standalone long-term memory entry (distinct from a raw
    chat message) — e.g. a fact the agent decided was worth
    remembering beyond just this one exchange.
    """
    db = SessionLocal()

    try:
        item = LongTermMemory(
            thread_id=thread_id,
            memory=memory,
            created_at=datetime.utcnow()
        )

        db.add(item)
        db.commit()

        return "Memory saved successfully."

    finally:
        db.close()


def search_memory(thread_id: str, query: str):
    """
    Retrieves recent long-term memory entries for a thread.

    NOTE: despite the name and the `query` parameter, this does NOT
    actually filter by relevance to `query` — it just returns the 20
    most recent memory entries for the thread, full stop. If you want
    real semantic search (only return memories relevant to `query`),
    you'd need something like embeddings + a vector similarity search
    instead of this. Treat this as a placeholder to upgrade later.
    """
    db = SessionLocal()

    try:
        memories = (
            db.query(LongTermMemory)
            .filter(LongTermMemory.thread_id == thread_id)
            .order_by(LongTermMemory.created_at.desc())
            .limit(20)
            .all()
        )

        if not memories:
            return "No saved memory found."

        return "\n".join([f"- {m.memory}" for m in memories])

    finally:
        db.close()